apiVersion: ENC[AES256_GCM,data:ids=,iv:/1O6ZsCHIMnE2uN1gyPv9ODgNyrlWieIbN6G92Fp7cc=,tag:oMLqbRf8E7qWszluN5p/IA==,type:str]
kind: ENC[AES256_GCM,data:BXGHwCqy,iv:e2srEoT4Pgi6TffIZjJlw5bDph41sl5zerdTqhWvhho=,tag:zJJZqGYgBJ3mRFN7QxANiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:z8rhzXaPQbWF,iv:15dWiMiaEfZf1dLXNtAeXDp2awYmUrSb+ifaRW8OFaE=,tag:UfvVpq26l8t2y4IBqagvNg==,type:str]
type: ENC[AES256_GCM,data:Mh6BrHEy,iv:tAD8xzsDdCXRMGxXFJpSKyzDb4Dg7zSbnOy2sF4ApTM=,tag:MMQCm8JYAa7bBdlkAQMccg==,type:str]
data:
    USERNAME: ENC[AES256_GCM,data:5oxoL9s=,iv:erZDDY7fzcRQv5iyHkjylUrhUHUN9mjZS4RBakP5SPY=,tag:Ewqdjvytxyj4Ccmp+EMrwg==,type:str]
    PASSWORD: ENC[AES256_GCM,data:uRvdSiA=,iv:CLnLaX4QZfZOslQQgeViqu/biKeTg4iOFbp+jkV0l0A=,tag:1y3O5AhfthZljr3rdtEQig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-23T03:16:18Z"
    mac: ENC[AES256_GCM,data:zmHx1YWoux28/ypT8lH382LaVhyMvlCNqrkX1wlJJn2JAaM+/VfvkH26LoWGbZly/eglhG6CrBvb2ooZRAYTu8iY5yUJDFNRkodNNJVpNm4SR1jqA7wV2E3IpRfXuhZhiRr/J/t+VpgLv7CvEaH2nFN6toPc8V7FoQ911Rm0vqk=,iv:twFwlelkP3I6gaIOCFLxD3Yi+f5gF7hFy4EKdQfOHIA=,tag:qzno8scqlybKv1E/9ufI4A==,type:str]
    pgp:
        - created_at: "2023-10-23T03:16:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMAyO3WGzKvWDvAQgAW5WDcpaZxyjz3pNreyKYkIEsMHZW+B4HumvH84GKLS4J
            dMtJwfBqB/gZ2N+obcQ2VWcMGZxg4iSqgjO4bNc3n9kxfbQ79q2zgbVB5aFwxQQP
            1N0klPAloQ1QN4uWM8rb658IRXcslzhP0XRTX5lhORgANgY+H9E72Z0LgcSS7zVw
            IRQEixDKurwhQ6KoJWVezd5k73+Ql99ZPJqvCZT5MwCxYBAR2r7cnESwtl3tJHNY
            jnensUtTV20kg2crXD/iLabHTCNdSmb0rMEuRbqf7Y1pyNXqnFznVKy+QuLtFAJC
            iRA6f88IVc2V1ATqR5BSGpCunRmOzg06+lxlC8scPNLmAcKlsREhUFNWRx2UBlD7
            s8tnw+P0Wy3HbBrEHaISmn4/U3dB8vV5HmmHd9a6PuZebKROinu3mQXVXC45D2xa
            d+RW3tN15Zm4Y7Qmq4oHniIx4pVsCv4A
            =l6vR
            -----END PGP MESSAGE-----
          fp: 09DBD52E3D62A8594BA887339C12D1D66094E4FC
    unencrypted_suffix: _unencrypted
    version: 3.7.1
